//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiThreading {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiThreading.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &quot;Name&quot;, &quot;Team&quot;, &quot;Position&quot;, &quot;Height(inches)&quot;, &quot;Weight(lbs)&quot;, &quot;Age&quot;
        ///&quot;Adam Donachie&quot;, &quot;BAL&quot;, &quot;Catcher&quot;, 74, 180, 22.99
        ///&quot;Paul Bako&quot;, &quot;BAL&quot;, &quot;Catcher&quot;, 74, 215, 34.69
        ///&quot;Ramon Hernandez&quot;, &quot;BAL&quot;, &quot;Catcher&quot;, 72, 210, 30.78
        ///&quot;Kevin Millar&quot;, &quot;BAL&quot;, &quot;First Baseman&quot;, 72, 210, 35.43
        ///&quot;Chris Gomez&quot;, &quot;BAL&quot;, &quot;First Baseman&quot;, 73, 188, 35.71
        ///&quot;Brian Roberts&quot;, &quot;BAL&quot;, &quot;Second Baseman&quot;, 69, 176, 29.39
        ///&quot;Miguel Tejada&quot;, &quot;BAL&quot;, &quot;Shortstop&quot;, 69, 209, 30.77
        ///&quot;Melvin Mora&quot;, &quot;BAL&quot;, &quot;Third Baseman&quot;, 71, 200, 35.07
        ///&quot;Aubrey Huff&quot;, &quot;BAL&quot;, &quot;Th [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string mlb_players {
            get {
                return ResourceManager.GetString("mlb_players", resourceCulture);
            }
        }
    }
}
